language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - ruby-head
  - ruby
  - 2.1.1
  - jruby-head
  - jruby
  - rbx-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby
    - rvm: jruby-head
    - rvm: jruby
    - rvm: rbx-head